services:
  - type: web
    name: gielda-operacje
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.13.0
      - key: ETORO_API_KEY
        sync: false
      - key: ETORO_USER_KEY
        sync: false
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
